version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            make docker

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: master
