version: 2

jobs:
  build:
    working_directory: ~/app
    shell: /bin/bash
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            make docker-ci
workflows:
  version: 2
  main:
    jobs:
    - build
